name: Deploy Vite React Frontend

on:
  push:
    branches: [ "main" ]  # Triggers deployment when pushing to main

permissions:
  contents: write  # Required for GitHub Pages deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build project
        working-directory: frontend
        run: npm run build

      - name: Create CNAME file
        run: echo "remiel.fyi" > frontend/dist/CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: frontend/dist  # Deploy the built frontend
          clean: true
